<?php

// 1- ENTRAR COM UMA PALAVRA E O NÚMERO DE VEZES QUE SE DESEJA
// IMPRIMIR A PALAVRA, E IMPRIMIR

$palavra="ola";
$numero=5;

// 2- ESCREVA UM ALGORITMO QUE LEIA TRÊS NÚMEROS, CALCULE SUA 
// MÉDIA NA VARIÁVEL MEDIA E EXIBA PARA O USUÁRIO O RESULTADO

$n1=10;
$n2=9;
$n3=5;

$media = ($n1 +$n2+ $n3) /3;

echo $media;

// 3- ESCREVA UM ALGORITMO QUE LEIA A VELOCIDADE DE UM OBJETO
// EM M/S (METROS POR SEGUNDO), CALCULE E EXIBA PARA O
// USUÁRIO A VELOCIDADE EM KM/H

$velocidadeMs; 

$velocidadeKm = velocidadeMs * 3.6;

echo 

// 4- ENTRAR COM NOME, SEXO E IDADE DE UMA PESSOA. SE A PESSOA FOR
// DO SEXO FEMININO E TIVER MENOS QUE 25 ANOS, IMPRIMIR NOME E A
// MENSAGEM: ACEITA. CASO CONTRÁRIO, IMPRIMIR NOME E A
// MENSAGEM: NÃO ACEITA

$nome="guilherme";
$sexo="masculino";
$idade="24";

if($sexo = "feminino" & $idade<25){
    echo $nome."Aceita";
}else{
echo $nome."Não Aceita";
}

// 5- ENTRAR COM 3 NÚMEROS E IMPRIMI-LOS EM ORDEM DECRESCENTE
// (SUPONHA NÚMEROS DIFERENTES)


// 6- LER UM NÚMERO INTEIRO ENTRE 1 E 12 E ESCREVER O MÊS
// CORRESPONDENTE. CASO O NÚMERO SEJA FORA DESSE INTERVALO,
// INFORMAR QUE NÃO EXISTE MÊS COM ESTE NÚMERO



$n1=4;
$n2=8;
$n3=5;




?>