<!-- ESCREVA UM PROGRAMA EM PHP QUE DECLARE UM ARRAY A PARTIR DE UMA STRING COM NOME “LISTA”, E QUE OS RETORNOS COM O COMANDO ECHO SEJAM OS SEGUINTES:
O ARRAY POR COMPLETO UTILIZANDO EXPLODE
O TAMANHO DO ARRAY
UMA VARIÁVEL NOVA A PARTIR DA INICIAL COM DIVISÃO EM QUEBRA DE LINHA
UTILIZANDO PELO MENOS DUAS FUNÇÕES DE LAÇO, E EXECUTANDO ATRAVÉS DE FUNCTIONS, IMPRIMA OS NÚMEROS DE 1 A 15 COM QUEBRAS DE LINHAS -->

<?php



?>